framework:
    messenger:
        failure_transport: failed_default
        transports:
            auth:
                dsn: '%env(MESSENGER_TRANSPORT_RABBIT)%'
                serializer: Gateway\Component\Serializer\ExternalJsonMessageSerializer
                options:
                    exchange:
                        name: gateway_auth
                        type: direct
                    queues:
                        gateway_auth: ~
            failed_default: '%env(MESSENGER_TRANSPORT_FAILED)%'
#            failed_default: 'doctrine://default?queue_name=failed_default'

        routing:
            # 'App\Message\YourMessage': async
            'Gateway\Infrastructure\Messager\Message\Auth\RefreshTokenMessage': auth
#            'Gateway\Message\AcceptRefreshTokenJob': auth
