lexik_jwt_authentication:
    secret_key: '%env(resolve:AUTH_JWT_SECRET_KEY)%'
    public_key: '%env(resolve:AUTH_JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(AUTH_JWT_PASSPHRASE)%'
    token_ttl: 3600 # in seconds, default is 3600   
    user_identity_field: login